{% set name = "tracktable-data" %}
{% set version = "1.7.3.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# We check out the repository instead of pulling a tarball so that the
# Git LFS references will be resolved.
source:
  git_url: https://github.com/sandialabs/tracktable-data
  git_rev: v1.7.3.1

build:
  noarch: python
  number: 1

requirements:
 build:
    - python
    - git
    - git-lfs
    - pip
    - python-build
    - setuptools

 host:
    - python {{ python_min }}
    - git
    - git-lfs
    - pip
    - python-build
    - setuptools

 run:
    - python >={{ python_min }}

test:
  imports:
    - tracktable_data
    - tracktable_data.data
    - tracktable_data.python_info_data
    - tracktable_data.python_example_data
    - tracktable_data.internal_test_data
  commands:
    - python -c "from tracktable_data.data import retrieve; files = retrieve(); assert len(files) > 0"
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://tracktable.sandia.gov/
  license_file: LICENSE.txt
  license: BSD-2-Clause
  license_url: https://opensource.org/licenses/BSD-2-Clause
  license_family: BSD
  summary: 'Trajectory Analysis and Rendering'
  description: >
    Tracktable-Data is a supplimental data package for the Tracktable library.
    Refer to the Tracktable documentation and Github repository for more
    information on Tracktable's capabilities and usage.
  dev_url: https://github.com/sandialabs/tracktable-data
  doc_url: https://tracktable.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pabaxley
    - atwilso
